check for nonstandard tools before executing

diff --git a/.local/bin/zellij-sessionizer b/.local/bin/zellij-sessionizer
--- a/.local/bin/zellij-sessionizer
+++ b/.local/bin/zellij-sessionizer
@@ -12,17 +12,11 @@ fi
 if [[ -n $1 ]]; then
   cd $1
   ZELLIJ_SESSION_DIR=$PWD
-  # if [[ $ZELLIJ_SESSION_DIR == '.' ]]; then
-  #   ZELLIJ_SESSION_DIR=$PWD
-  # elif [[ ! $ZELLIJ_SESSION_DIR =~ '^/.*' ]]; then
-  #   [[ -d $PWD/$ZELLIJ_SESSION_DIR ]] && \
-  #     ZELLIJ_SESSION_DIR=$PWD/$ZELLIJ_SESSION_DIR
-  # fi
 else
-  # FOUND=$(fd -HI . $SHORTCUTS --exact-depth 1 --type d)
-  # CLASSES=$(classfind)
-  # REPOS=$(repofind)
-  # ZELLIJ_SESSION_DIR=$(echo "$HOME\n$FOUND\n$CLASSES\n$REPOS" | sort -u | fzf)
+  if ! command -v fzf &> /dev/null; then
+    echo "ERROR: fzf missing (install fzf or use as 'zellij-sessionizer DIR')"
+    exit 1
+  fi
   ZELLIJ_SESSION_DIR=$(printf "%s\n" $ZELLIJ_SHORTCUTS | sort -u | fzf)
 fi
 
