sh: formatted all scripts with beautysh

diff --git a/.config/sessionizer b/.config/sessionizer
--- a/.config/sessionizer
+++ b/.config/sessionizer
@@ -3,61 +3,61 @@ sessionizer_shortcuts=($HOME $HOME/.dotfiles $HOME/.dotfiles/.config/nvim)
 
 # code
 if [[ -d $CODEPATH ]]; then
-  if command -v fd &> /dev/null; then
-    sessionizer_shortcuts+=(\
-      $(fd -HI '.git$' $CODEPATH | sed 's|\.git/\?||'))
-  else
-    sessionizer_shortcuts+=(\
-      $(find $CODEPATH -name ".git" | sed 's|\.git/\?||'))
-  fi
+    if command -v fd &> /dev/null; then
+        sessionizer_shortcuts+=(\
+            $(fd -HI '.git$' $CODEPATH | sed 's|\.git/\?||'))
+    else
+        sessionizer_shortcuts+=(\
+            $(find $CODEPATH -name ".git" | sed 's|\.git/\?||'))
+    fi
 fi
 
 # cloud
 if [[ -d $HOME/cloud ]]; then
-  edu=$HOME/cloud/edu
-  cyb=$HOME/cloud/tech/cyber
+    edu=$HOME/cloud/edu
+    cyb=$HOME/cloud/tech/cyber
 
-  if command -v fd &> /dev/null; then
-    [[ -d $edu ]] && sessionizer_shortcuts+=(\
-      $(fd -u . $edu --exact-depth 3 -t d))
-    [[ -d $cyb ]] && sessionizer_shortcuts+=(\
-      $(fd -u . $cyb --exact-depth 1 -t d))
-  else
-    [[ -d $edu ]] && sessionizer_shortcuts+=(\
-      $(find $edu -mindepth 3 -maxdepth 3 -type d))
-    [[ -d $cyb ]] && sessionizer_shortcuts+=(\
-      $(find $cyb -mindepth 3 -maxdepth 3 -type d))
-  fi
+    if command -v fd &> /dev/null; then
+        [[ -d $edu ]] && sessionizer_shortcuts+=(\
+            $(fd -u . $edu --exact-depth 3 -t d))
+        [[ -d $cyb ]] && sessionizer_shortcuts+=(\
+            $(fd -u . $cyb --exact-depth 1 -t d))
+    else
+        [[ -d $edu ]] && sessionizer_shortcuts+=(\
+            $(find $edu -mindepth 3 -maxdepth 3 -type d))
+        [[ -d $cyb ]] && sessionizer_shortcuts+=(\
+            $(find $cyb -mindepth 3 -maxdepth 3 -type d))
+    fi
 fi
 
 sessionizer() {
-  if [[ -n $1 ]]; then
-    [[ ! -d $1 ]] && {
-      echo "EXIT: $1 isn't a directory"
-      exit
-    }
-    sessionizer_dir=$(realpath $1)
-  else
-    if ! command -v fzf &> /dev/null; then
-      echo "ERROR: install fzf or specify dir: $(basename $0) DIR"
-      exit 1
+    if [[ -n $1 ]]; then
+        [[ ! -d $1 ]] && {
+            echo "EXIT: $1 isn't a directory"
+            exit
+        }
+        sessionizer_dir=$(realpath $1)
+    else
+        if ! command -v fzf &> /dev/null; then
+            echo "ERROR: install fzf or specify dir: $(basename $0) DIR"
+            exit 1
+        fi
+
+        # LC_COLLATE=C forces sorting by ASCII values
+        sessionizer_dir=$(printf "%s\n" "${sessionizer_shortcuts[@]}" |\
+            sed 's|/$||'| LC_COLLATE=C sort -u | fzf)
     fi
 
-    # LC_COLLATE=C forces sorting by ASCII values
-    sessionizer_dir=$(printf "%s\n" "${sessionizer_shortcuts[@]}" |\
-      sed 's|/$||'| LC_COLLATE=C sort -u | fzf)
-  fi
+    [[ -z $sessionizer_dir ]] && {
+        echo "EXIT: session dir not chosen"
+        exit
+    }
 
-  [[ -z $sessionizer_dir ]] && {
-    echo "EXIT: session dir not chosen"
-    exit
-  }
-
-  if [[ $sessionizer_dir == $HOME ]]; then
-    sessionizer_name=HOME
-  else
-    sessionizer_name=$(basename "$sessionizer_dir")
-  fi
+    if [[ $sessionizer_dir == $HOME ]]; then
+        sessionizer_name=HOME
+    else
+        sessionizer_name=$(basename "$sessionizer_dir")
+    fi
 }
 
 
diff --git a/.local/bin/ssh-copy-terminfo b/.local/bin/ssh-copy-terminfo
--- a/.local/bin/ssh-copy-terminfo
+++ b/.local/bin/ssh-copy-terminfo
@@ -1,28 +1,28 @@
 #! /usr/bin/env bash
 
 if [[ -z $1 ]]; then
-	echo "Error: No user@host"
-	echo "Usage: $0 user@host"
-	exit 1
+    echo "Error: No user@host"
+    echo "Usage: $0 user@host"
+    exit 1
 fi
 
 if [[ $2 == "-t" || $2 == "--test" ]]; then
-	echo "Testing testing..." | ssh "$1" 'cat - > ssh-copy-terminfo-test'
-	if [[ $? == 0 ]]; then
-		echo "Tentative Success: Please use 'ssh $1' and"
-		echo "look for ~/ssh-copy-terminfo-test to confirm"
-	else
-		echo "Tentative Failure: Please use 'ssh $1' and"
-		echo "look for ~/ssh-copy-terminfo-test to confirm"
-	fi
-	exit
+    echo "Testing testing..." | ssh "$1" 'cat - > ssh-copy-terminfo-test'
+    if [[ $? == 0 ]]; then
+        echo "Tentative Success: Please use 'ssh $1' and"
+        echo "look for ~/ssh-copy-terminfo-test to confirm"
+    else
+        echo "Tentative Failure: Please use 'ssh $1' and"
+        echo "look for ~/ssh-copy-terminfo-test to confirm"
+    fi
+    exit
 fi
 
 infocmp -x | ssh "$1" 'tic -x -'
 if [[ $? == 0 ]]; then
-	echo "Tentative Success: Please use 'ssh $1' and"
-	echo "look for /usr/share/terminfo/${TERM:0:1}/$TERM to confirm"
+    echo "Tentative Success: Please use 'ssh $1' and"
+    echo "look for /usr/share/terminfo/${TERM:0:1}/$TERM to confirm"
 else
-	echo "Tentative Failure: Please use 'ssh $1' and"
-	echo "look for /usr/share/terminfo/${TERM:0:1}/$TERM to confirm"
+    echo "Tentative Failure: Please use 'ssh $1' and"
+    echo "look for /usr/share/terminfo/${TERM:0:1}/$TERM to confirm"
 fi
